In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Bollywood.csv')

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## 1.Selecting Column

In [4]:
df[["Actor",]]

                 Actor
0       Shah Rukh Khan
1          Salman Khan
2           Aamir Khan
3        Ranbir Kapoor
4        Ranveer Singh
5   Ayushmann Khurrana
6        Rajkummar Rao
7       Hrithik Roshan
8         Akshay Kumar
9        Kartik Aaryan
10        Varun Dhawan
11       Vicky Kaushal

In [5]:
df[["Actor","Film","Year"]]

                 Actor                      Film  Year
0       Shah Rukh Khan                   Pathaan  2023
1          Salman Khan           Tiger Zinda Hai  2017
2           Aamir Khan                    Dangal  2016
3        Ranbir Kapoor                Brahmastra  2022
4        Ranveer Singh                 Padmaavat  2018
5   Ayushmann Khurrana                 Andhadhun  2018
6        Rajkummar Rao                     Stree  2018
7       Hrithik Roshan                       War  2019
8         Akshay Kumar                Good Newwz  2019
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022
10        Varun Dhawan     Badrinath Ki Dulhania  2017
11       Vicky Kaushal  Uri: The Surgical Strike  2019

## 2.Selecting Rows by Index

In [6]:
df.loc[[0]]

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [7]:
df.loc[[0,1,2,3,5,7,10]]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1

In [11]:
df.iloc[[0]]

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [14]:
df.iloc[[1,4,8]]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0

## 3.Select Specific Rows and Columns

In [21]:
df.loc[1, "Actor"]

'Salman Khan'

In [22]:
df.loc[0, "IMDb"]

np.float64(7.2)

In [28]:
df.iloc[0, 1]

'Pathaan'

In [33]:
df.iloc[0:2, 0]

0    Shah Rukh Khan
1       Salman Khan
Name: Actor, dtype: object

In [34]:
df.iloc[0:10, 0:2]

                Actor               Film
0      Shah Rukh Khan            Pathaan
1         Salman Khan    Tiger Zinda Hai
2          Aamir Khan             Dangal
3       Ranbir Kapoor         Brahmastra
4       Ranveer Singh          Padmaavat
5  Ayushmann Khurrana          Andhadhun
6       Rajkummar Rao              Stree
7      Hrithik Roshan                War
8        Akshay Kumar         Good Newwz
9       Kartik Aaryan  Bhool Bhulaiyaa 2

In [35]:
df.iloc[0:5, 0:3]

            Actor             Film  Year
0  Shah Rukh Khan          Pathaan  2023
1     Salman Khan  Tiger Zinda Hai  2017
2      Aamir Khan           Dangal  2016
3   Ranbir Kapoor       Brahmastra  2022
4   Ranveer Singh        Padmaavat  2018

In [36]:
df.loc[0:2, ["Actor", "Film"]]

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai
2      Aamir Khan           Dangal

In [37]:
df.loc[0:5, ["Actor", "Film","Year","IMDb"]]

                Actor             Film  Year  IMDb
0      Shah Rukh Khan          Pathaan  2023   7.2
1         Salman Khan  Tiger Zinda Hai  2017   6.0
2          Aamir Khan           Dangal  2016   8.4
3       Ranbir Kapoor       Brahmastra  2022   5.6
4       Ranveer Singh        Padmaavat  2018   7.0
5  Ayushmann Khurrana        Andhadhun  2018   8.3

In [41]:
df.iloc[0:5, 0:6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0

## 4.Fast Access: .at and .iat
These are optimized for single element access:

In [45]:
df.at[0,"Actor"]

'Shah Rukh Khan'

In [46]:
df.iat[0,0]

'Shah Rukh Khan'

In [47]:
df.iat[5,5]

np.float64(8.3)

In [48]:
df.iat[1,0]

'Salman Khan'

## 5.Filtering with Conditions

In [49]:
df[df["IMDb"]>6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [55]:
df[(df["IMDb"]>7) & (df["Year"]>2020)]

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [56]:
df[df["BoxOffice(INR Crore)"]>500]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0

In [61]:
df[(df["BoxOffice(INR Crore)"]>500) | (df["Year"]>2020) ]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

## - Querying with .query()

In [3]:
import pandas as pd

In [6]:
df = pd.read_csv("Bollywood.csv")

In [7]:
df.query("Year > 2020")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

In [9]:
df.query("Year > 2020 and IMDb > 6")

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [14]:
col = "Year"
df.query(f"{col} > 2018 ")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [19]:
df.query("`BoxOffice(INR Crore)` > 500 and Genre == 'Action'")

            Actor             Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan          Pathaan  2023  Action                  1050   7.2
1     Salman Khan  Tiger Zinda Hai  2017  Action                   565   6.0

In [22]:
df.query("Year > 2019 and Genre == 'Action' and IMDb > 5")

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [23]:
df2 = df[['Actor', 'IMDb']].copy()

In [24]:
df2

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [25]:
df2.loc[0, 'Actor'] = "Harry"

In [26]:
df2

                 Actor  IMDb
0                Harry   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [27]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2