## **Merging & Joining Data**
Often, data is split across multiple tables or files. Pandas lets you combine them just like SQL — or even more flexibly!

**Sample DataFrames**

In [4]:
import  pandas as pd

In [5]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [15]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [16]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

## Merge Like SQL: pd.merge()
Inner Join (default)

In [7]:
pd.merge(employees, departments, on="DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

**1.Left Join**

In [8]:
pd.merge(employees, departments, on="DeptID", how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

Keeps all employees, fills NaN where no match.

**2.Right Join**

In [9]:
pd.merge(employees, departments, on="DeptID", how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

Keeps all departments, even if no employee

## 3.Outer Join

In [10]:
pd.merge(employees, departments, on="DeptID", how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

Includes all data, fills missing with NaN.

## Concatenating DataFrames
Use pd.concat() to stack datasets either vertically or horizontally.

**Vertical (rows)**

In [11]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

**Horizontal (columns)**

In [12]:
df1 = pd.DataFrame({"ID": [1, 2]})
df2 = pd.DataFrame({"Score": [90, 80]})

pd.concat([df1, df2], axis=1)

   ID  Score
0   1     90
1   2     80

### When to Use What?

| Use Case                               | Method                                                |
|----------------------------------------|-------------------------------------------------------|
| SQL-style joins (merge keys)           | `pd.merge()` or `.join()`                             |
| Stack datasets vertically               | `pd.concat([df1, df2])`                               |
| Combine different features side-by-side | `pd.concat([df1, df2], axis=1)`                       |
| Align on index                          | `.join()` or `merge(..., right_index=True)`           |

## Summary
- Use merge() like SQL joins (inner, left, right, outer)
- Use concat() to stack DataFrames (rows or columns)
- Handle mismatched keys and indexes with care
- Merging and joining are essential for real-world projects